# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  greeting:
    cmds:
      - echo "ANOTHER {{.GREETING}}"
      - pwd
    silent: true
  ps:
    cmds:
      - docker -v
    silent: true 
